# Generated by Django 5.2.5 on 2025-09-01 04:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=django.utils.timezone.now)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='matches.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_from', '-id'],
                'indexes': [models.Index(fields=['user', 'date_to'], name='matches_tea_user_id_03622c_idx'), models.Index(fields=['user', 'date_from'], name='matches_tea_user_id_617903_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('date_to__isnull', True)), fields=('user',), name='uniq_user_active_membership')],
            },
        ),
    ]
