# Generated by Django 5.2.5 on 2025-09-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_location_match_enrollment_matchfaq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
