# Generated by Django 5.2.5 on 2025-09-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_created_at_alter_match_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_identifier',
            field=models.UUIDField(null=True, unique=True, editable=False, db_index=True),
        ),
    ]
