# Generated by Django 5.2.5 on 2025-09-08 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_backfill_match_identifier_and_set_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['match', 'joined_at'], name='matches_enr_match_i_135a00_idx'),
        ),
    ]
