# Generated by Django 5.2.5 on 2025-09-06 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0006_backfill_match_identifier_and_set_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('preference_id', models.CharField(blank=True, max_length=120)),
                ('init_point', models.URLField(blank=True, max_length=1000)),
                ('sandbox_init_point', models.URLField(blank=True, max_length=1000)),
                ('mp_payment_id', models.CharField(blank=True, max_length=120)),
                ('mp_status', models.CharField(blank=True, max_length=50)),
                ('external_reference', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed_capacity', 'Failed capacity')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['external_reference'], name='payments_pa_externa_e30da4_idx'), models.Index(fields=['status', 'match'], name='payments_pa_status_65010c_idx')],
            },
        ),
    ]
