# Generated by Django 5.2.5 on 2025-09-07 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_backfill_match_identifier_and_set_default'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'in_process'])), fields=('user', 'match'), name='uniq_active_payment_per_user_match'),
        ),
    ]
