# Generated by Django 5.2.5 on 2025-09-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_termsandconditions_section_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
