# Generated by Django 5.2.5 on 2025-09-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_termsandconditions_version'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='termsandconditions',
            index=models.Index(fields=['section', 'is_active', 'published_at'], name='accounts_te_section_afe743_idx'),
        ),
        migrations.AddConstraint(
            model_name='termsandconditions',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('section', 'is_active'), name='uniq_active_terms_per_section'),
        ),
        migrations.AddConstraint(
            model_name='termsandconditions',
            constraint=models.UniqueConstraint(fields=('section', 'version'), name='uniq_terms_section_version'),
        ),
    ]
