# Generated by Django 5.2.5 on 2025-09-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_termsandconditions_accounts_te_section_afe743_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
